export const TOGGLE_SELECT_HOME_BREAD = 'TOGGLE_SELECT_HOME_BREAD'
export const END_SELECTING = 'END_SELECTING'
export const DONE_TOSTING = 'DONE_TOSTING'

export const ADD_INGR = 'ADD_INGR'
export const REMOVE_INGR = 'REMOVE_INGR'

export const ADD_NAME = 'ADD_NAME'